"""LLM integration (OpenAI-compatible, e.g. Kimi/Moonshot) for the monitor.

When ``llm.enabled`` is true in config.json, three outputs are generated by
the configured model instead of the rule-based code:

- 今日选股 Top N   (select mode  -> candidates.json)
- 预警记录         (monitor mode -> alerts.json)
- 日报预览/收盘日报 (report mode  -> daily_report.json + report_*.md)

Every public function returns ``None`` on any failure (network, auth,
unparseable output) so callers can fall back to the rule-based path.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import date
from typing import Any, Dict, List, Optional

import requests

from config import LLMConfig

logger = logging.getLogger(__name__)


class LLMError(Exception):
    """Raised when an LLM call or response parsing fails."""


# ---------------------------------------------------------------------------
# Low-level client
# ---------------------------------------------------------------------------

def chat(cfg: LLMConfig, system: str, user: str) -> str:
    """Send one system+user chat completion and return the reply text.

    Raises ``LLMError`` on missing credentials, HTTP errors, or malformed
    responses.
    """
    if not cfg.api_key:
        raise LLMError("未配置 llm.api_key")
    url = cfg.base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": cfg.model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": cfg.temperature,
        # 结构化 JSON 输出不需要思考过程，关掉以节省 token、加快响应
        "thinking": {"type": "disabled"},
    }
    try:
        resp = requests.post(
            url,
            json=payload,
            headers={"Authorization": f"Bearer {cfg.api_key}"},
            timeout=cfg.timeout,
        )
        resp.raise_for_status()
        data = resp.json()
        return data["choices"][0]["message"]["content"]
    except requests.RequestException as exc:
        raise LLMError(f"LLM 请求失败: {exc}") from exc
    except (KeyError, IndexError, TypeError, ValueError) as exc:
        raise LLMError(f"LLM 响应格式异常: {exc}") from exc


def _extract_json(text: str) -> Any:
    """Parse JSON from an LLM reply, tolerating code fences and prose."""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    m = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            pass
    for open_ch, close_ch in (("[", "]"), ("{", "}")):
        start = text.find(open_ch)
        end = text.rfind(close_ch)
        if start != -1 and end > start:
            try:
                return json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                continue
    raise LLMError(f"无法从模型回复中解析 JSON: {text[:200]}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _compact_row(row: Dict[str, Any]) -> Dict[str, Any]:
    """Shrink one data row for the prompt: round floats, keep the rest.

    Strings (e.g. ``code="000001"``) are passed through untouched so
    leading zeros survive.
    """
    out: Dict[str, Any] = {}
    for k, v in row.items():
        if isinstance(v, str) or v is None:
            out[k] = v if v is not None else ""
            continue
        try:
            out[k] = round(float(v), 4)  # covers int/float/numpy numbers/bool
        except (TypeError, ValueError):
            out[k] = str(v)
    return out


def _to_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _resolve_code(raw: Any, known_codes: Dict[str, Dict[str, Any]]) -> Optional[str]:
    """Match an LLM-returned code to an input row, tolerating int coercion."""
    code = str(raw if raw is not None else "").strip()
    if code in known_codes:
        return code
    # e.g. model emitted 1 instead of "000001"
    if code.isdigit() and len(code) < 6:
        padded = code.zfill(6)
        if padded in known_codes:
            return padded
    return None


# ---------------------------------------------------------------------------
# Feature 1: 今日选股
# ---------------------------------------------------------------------------

_SELECT_SYSTEM = (
    "你是一位严谨的A股量化分析师，擅长结合技术面、成交量与板块热点选股。"
    "只输出要求的JSON，不要输出任何解释。"
)

_SELECT_USER = """以下是经过初步筛选的A股候选股票数据
（close现价, ma20二十日均线, volume_5d五日日均成交额, rsi14, macd_hist, pe市盈率,
high_20d/low_20d二十日高低点, change_20d二十日涨幅, sector板块, volume_today今日成交量）：

{rows_json}

今日板块涨幅排名（越靠前越热门）：{sector_rank}

请从中选出最值得关注的最多 {top_n} 只，按推荐程度从高到低排序。
要求：
1. 只输出JSON数组：[{{"code":"...","name":"...","score":85,"reason":"一句话中文理由"}}]
2. score 为 0-100 的整数，reason 不超过50字
3. code 必须来自输入列表，不得编造
4. 若没有值得推荐的，输出 []"""


def select_stocks(
    rows: List[Dict[str, Any]],
    cfg: LLMConfig,
    top_n: int = 5,
    sector_rank: Optional[List[str]] = None,
) -> Optional[List[Dict[str, Any]]]:
    """Ask the LLM to rank *rows*; return picked rows with score+reason.

    Each returned dict is the original row plus ``score`` (0-100) and a
    Chinese ``reason``.  Returns ``None`` on failure (caller falls back to
    the rule-based ``screen_stocks``).
    """
    if not rows:
        return []
    try:
        user = _SELECT_USER.format(
            rows_json=json.dumps(
                [_compact_row(r) for r in rows], ensure_ascii=False, default=str
            ),
            sector_rank="、".join(sector_rank) if sector_rank else "（无数据）",
            top_n=top_n,
        )
        parsed = _extract_json(chat(cfg, _SELECT_SYSTEM, user))
        if not isinstance(parsed, list):
            raise LLMError("选股结果不是 JSON 数组")

        by_code = {str(r.get("code", "")): r for r in rows}
        picked: List[Dict[str, Any]] = []
        for item in parsed:
            if not isinstance(item, dict):
                continue
            code = _resolve_code(item.get("code"), by_code)
            if code is None:
                continue
            picked.append({
                **by_code[code],
                "score": _to_float(item.get("score")),
                "reason": str(item.get("reason", "")),
            })
        picked.sort(key=lambda r: r["score"], reverse=True)
        return picked[:top_n]
    except LLMError as exc:
        logger.warning("LLM 选股失败: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Feature 2: 预警记录
# ---------------------------------------------------------------------------

_ALERT_SYSTEM = (
    "你是一位A股盘中异动监控助手，负责从自选股实时数据中识别值得提醒的异动。"
    "只输出要求的JSON，不要输出任何解释。"
)

_ALERT_USER = """自选股实时数据
（price现价, change_pct涨跌幅%, volume今日成交量, volume_5d_avg五日日均成交量,
high_20d二十日高点, low_20d二十日低点）：

{rows_json}

请识别需要提醒的异动（如大涨大跌、明显放量、突破或跌破二十日高低点等）。
要求：
1. 只输出JSON数组：[{{"code":"...","name":"...","price":12.5,"change_pct":6.0,"reason":"中文一句话说明","level":"HIGH"}}]
2. level 只能是 HIGH（重大异动）或 MEDIUM（一般异动）
3. code 必须来自输入列表，不得编造
4. 没有异动则输出 []"""


def generate_alerts(
    rows: List[Dict[str, Any]],
    cfg: LLMConfig,
) -> Optional[List[Dict[str, Any]]]:
    """Ask the LLM to spot anomalies in watchlist rows.

    Returns alert dicts in the same shape as ``AlertEngine.process_alerts``
    (``timestamp`` left empty for the caller to stamp), or ``None`` on
    failure so the caller can fall back to the rule engine.  An empty list
    is a valid result meaning "no anomalies".
    """
    if not rows:
        return []
    try:
        user = _ALERT_USER.format(
            rows_json=json.dumps(
                [_compact_row(r) for r in rows], ensure_ascii=False, default=str
            ),
        )
        parsed = _extract_json(chat(cfg, _ALERT_SYSTEM, user))
        if not isinstance(parsed, list):
            raise LLMError("异动识别结果不是 JSON 数组")

        by_code = {str(r.get("code", "")): r for r in rows}
        alerts: List[Dict[str, Any]] = []
        for item in parsed:
            if not isinstance(item, dict):
                continue
            code = _resolve_code(item.get("code"), by_code)
            if code is None:
                continue
            reason = str(item.get("reason", "")).strip()
            if not reason:
                continue
            src = by_code[code]
            level = str(item.get("level", "MEDIUM")).upper()
            if level not in ("HIGH", "MEDIUM"):
                level = "MEDIUM"
            alerts.append({
                "code": code,
                "name": str(item.get("name") or src.get("name", "")),
                "price": _to_float(item.get("price", src.get("price"))),
                "change_pct": _to_float(
                    item.get("change_pct", src.get("change_pct"))
                ),
                "reason": reason,
                "level": level,
                "timestamp": "",
            })
        return alerts
    except LLMError as exc:
        logger.warning("LLM 异动识别失败: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Feature 3: 日报预览 / 收盘日报
# ---------------------------------------------------------------------------

_REPORT_SYSTEM = (
    "你是一位A股复盘分析师，负责撰写每日收盘日报，语气客观、数据准确。"
    "只输出要求的JSON，不要输出任何解释。"
)

_REPORT_USER = """今日日期：{report_date}

今日市场数据如下：

【大盘概况】{market_json}

【自选股表现】{watchlist_json}

【今日预警】{alerts_json}

【选股候选】{candidates_json}

请生成收盘日报，只输出如下JSON：
{{"title":"每日复盘","summary":"150字以内的中文复盘摘要","highlights":["要点1","要点2"],"markdown":"完整Markdown日报"}}

要求：
1. highlights 为 3-6 条一句话要点
2. markdown 包含 大盘概况 / 自选股表现 / 今日预警 / 明日关注 / 市场情绪 五个小节，中文撰写
3. 数据必须来自上述输入，不得编造"""


def generate_report(
    market: Dict[str, Any],
    watchlist_records: List[Dict[str, Any]],
    alert_records: List[Dict[str, Any]],
    candidate_records: List[Dict[str, Any]],
    cfg: LLMConfig,
    report_date: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Ask the LLM to write the daily report.

    Returns a dict with ``title`` / ``summary`` / ``highlights`` (for the
    frontend 日报预览 in daily_report.json) and ``markdown`` (full report),
    or ``None`` on failure so the caller falls back to the template report.
    ``report_date`` (e.g. ``"2026-07-18"``) is shown to the model so the
    report carries the correct date; defaults to today.
    """
    if not report_date:
        report_date = date.today().isoformat()
    try:
        user = _REPORT_USER.format(
            report_date=report_date,
            market_json=json.dumps(market, ensure_ascii=False, default=str),
            watchlist_json=json.dumps(
                [_compact_row(r) for r in watchlist_records],
                ensure_ascii=False, default=str,
            ),
            alerts_json=json.dumps(
                alert_records[-10:], ensure_ascii=False, default=str
            ),
            candidates_json=json.dumps(
                [_compact_row(r) for r in candidate_records[:5]],
                ensure_ascii=False, default=str,
            ),
        )
        parsed = _extract_json(chat(cfg, _REPORT_SYSTEM, user))
        if not isinstance(parsed, dict):
            raise LLMError("日报结果不是 JSON 对象")
        markdown = str(parsed.get("markdown", "")).strip()
        if not markdown:
            raise LLMError("日报 markdown 为空")
        highlights = parsed.get("highlights", [])
        if not isinstance(highlights, list):
            highlights = []
        return {
            "title": str(parsed.get("title", "每日复盘") or "每日复盘"),
            "summary": str(parsed.get("summary", "")),
            "highlights": [str(h) for h in highlights if h],
            "markdown": markdown,
        }
    except LLMError as exc:
        logger.warning("LLM 日报生成失败: %s", exc)
        return None


# =========================================================================
# Unit tests (pytest-compatible)
# =========================================================================

from unittest import mock  # noqa: E402


def _fake_response(payload: Dict[str, Any]) -> mock.Mock:
    resp = mock.Mock()
    resp.raise_for_status = mock.Mock()
    resp.json = mock.Mock(return_value=payload)
    return resp


def _chat_payload(content: str) -> Dict[str, Any]:
    return {"choices": [{"message": {"content": content}}]}


def _sample_rows() -> List[Dict[str, Any]]:
    return [
        {"code": "000001", "name": "平安银行", "close": 12.5, "ma20": 11.8,
         "volume_5d": 2e8, "rsi14": 58.0, "macd_hist": 0.05, "pe": 6.5,
         "high_20d": 12.8, "low_20d": 11.0, "change_20d": 0.06,
         "sector": "银行", "volume_today": 3e8, "macd_hist_prev": 0.03},
        {"code": "600519", "name": "贵州茅台", "close": 1680.0, "ma20": 1650.0,
         "volume_5d": 5e8, "rsi14": 55.0, "macd_hist": 2.1, "pe": 28.0,
         "high_20d": 1700.0, "low_20d": 1550.0, "change_20d": 0.03,
         "sector": "白酒", "volume_today": 6e8, "macd_hist_prev": 1.9},
        {"code": "300750", "name": "宁德时代", "close": 180.0, "ma20": 190.0,
         "volume_5d": 4e8, "rsi14": 35.0, "macd_hist": -1.2, "pe": 22.0,
         "high_20d": 195.0, "low_20d": 175.0, "change_20d": -0.08,
         "sector": "电池", "volume_today": 4.5e8, "macd_hist_prev": -1.0},
    ]


def _sample_alert_rows() -> List[Dict[str, Any]]:
    return [
        {"code": "000001", "name": "平安银行", "price": 12.5,
         "change_pct": 6.0, "volume": 5e7, "volume_5d_avg": 1e7,
         "high_20d": 12.0, "low_20d": 10.0},
        {"code": "600519", "name": "贵州茅台", "price": 1680.0,
         "change_pct": -0.5, "volume": 2e7, "volume_5d_avg": 2.5e7,
         "high_20d": 1700.0, "low_20d": 1550.0},
    ]


def _cfg() -> LLMConfig:
    return LLMConfig(enabled=True, api_key="test-key", model="kimi-k2.6")


class TestChat:
    def test_chat_success(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload("你好")),
        ) as post:
            assert chat(_cfg(), "sys", "user") == "你好"
            _, kwargs = post.call_args
            assert kwargs["headers"]["Authorization"] == "Bearer test-key"
            assert kwargs["json"]["model"] == "kimi-k2.6"
            assert kwargs["json"]["messages"][1]["content"] == "user"

    def test_chat_without_key_raises(self) -> None:
        cfg = LLMConfig(enabled=True, api_key="")
        try:
            chat(cfg, "sys", "user")
            assert False, "Expected LLMError"
        except LLMError as exc:
            assert "api_key" in str(exc)

    def test_chat_http_error_raises(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            side_effect=requests.ConnectionError("boom"),
        ):
            try:
                chat(_cfg(), "sys", "user")
                assert False, "Expected LLMError"
            except LLMError as exc:
                assert "请求失败" in str(exc)


class TestExtractJson:
    def test_plain(self) -> None:
        assert _extract_json('[{"a": 1}]') == [{"a": 1}]

    def test_fenced(self) -> None:
        assert _extract_json('```json\n{"a": 1}\n```') == {"a": 1}

    def test_embedded_in_prose(self) -> None:
        text = '分析结果如下：\n[{"code": "000001"}]\n以上。'
        assert _extract_json(text) == [{"code": "000001"}]

    def test_garbage_raises(self) -> None:
        try:
            _extract_json("没有任何JSON")
            assert False, "Expected LLMError"
        except LLMError:
            pass


class TestSelectStocks:
    def test_maps_back_and_sorts(self) -> None:
        reply = json.dumps([
            {"code": "600519", "score": 90, "reason": "白酒龙头放量突破"},
            {"code": "000001", "score": 75, "reason": "银行低估放量"},
            {"code": "999999", "score": 99, "reason": "编造代码应被丢弃"},
        ], ensure_ascii=False)
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload(reply)),
        ):
            picked = select_stocks(_sample_rows(), _cfg(), top_n=5)
        assert picked is not None
        assert [p["code"] for p in picked] == ["600519", "000001"]
        assert picked[0]["score"] == 90
        assert picked[0]["reason"] == "白酒龙头放量突破"
        # 原始字段保留
        assert picked[0]["close"] == 1680.0

    def test_int_code_padded(self) -> None:
        reply = json.dumps([{"code": 1, "score": 60, "reason": "补零匹配"}])
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload(reply)),
        ):
            picked = select_stocks(_sample_rows(), _cfg(), top_n=5)
        assert picked is not None and picked[0]["code"] == "000001"

    def test_top_n_limit(self) -> None:
        reply = json.dumps([
            {"code": "000001", "score": 80, "reason": "a"},
            {"code": "600519", "score": 70, "reason": "b"},
            {"code": "300750", "score": 60, "reason": "c"},
        ])
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload(reply)),
        ):
            picked = select_stocks(_sample_rows(), _cfg(), top_n=2)
        assert picked is not None and len(picked) == 2

    def test_bad_json_returns_none(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload("我不知道")),
        ):
            assert select_stocks(_sample_rows(), _cfg()) is None

    def test_http_error_returns_none(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            side_effect=requests.ConnectionError("boom"),
        ):
            assert select_stocks(_sample_rows(), _cfg()) is None

    def test_empty_input(self) -> None:
        assert select_stocks([], _cfg()) == []


class TestGenerateAlerts:
    def test_shape_and_level_normalization(self) -> None:
        reply = json.dumps([
            {"code": "000001", "price": 12.5, "change_pct": 6.0,
             "reason": "放量大涨", "level": "high"},
            {"code": "600519", "reason": "", "level": "MEDIUM"},
        ], ensure_ascii=False)
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload(reply)),
        ):
            alerts = generate_alerts(_sample_alert_rows(), _cfg())
        assert alerts is not None and len(alerts) == 1
        a = alerts[0]
        assert a["level"] == "HIGH"  # 小写被归一化
        assert a["name"] == "平安银行"  # 缺省 name 从输入回填
        assert set(a.keys()) == {
            "code", "name", "price", "change_pct", "reason", "level", "timestamp",
        }

    def test_no_anomaly_empty_list(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload("[]")),
        ):
            assert generate_alerts(_sample_alert_rows(), _cfg()) == []

    def test_failure_returns_none(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            side_effect=requests.Timeout("slow"),
        ):
            assert generate_alerts(_sample_alert_rows(), _cfg()) is None

    def test_empty_input(self) -> None:
        assert generate_alerts([], _cfg()) == []


class TestGenerateReport:
    def test_full_shape(self) -> None:
        reply = json.dumps({
            "title": "每日复盘",
            "summary": "今日市场缩量调整。",
            "highlights": ["上证跌1%", "银行抗跌"],
            "markdown": "# 日报\n\n内容",
        }, ensure_ascii=False)
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(_chat_payload(reply)),
        ):
            result = generate_report(
                {"index_name": "上证指数"}, [], [], [], _cfg()
            )
        assert result is not None
        assert result["markdown"].startswith("# 日报")
        assert result["summary"] == "今日市场缩量调整。"
        assert result["highlights"] == ["上证跌1%", "银行抗跌"]

    def test_missing_markdown_returns_none(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            return_value=_fake_response(
                _chat_payload('{"summary": "没有正文"}')
            ),
        ):
            assert generate_report({}, [], [], [], _cfg()) is None

    def test_failure_returns_none(self) -> None:
        with mock.patch(
            "llm_client.requests.post",
            side_effect=requests.ConnectionError("boom"),
        ):
            assert generate_report({}, [], [], [], _cfg()) is None
